# this is only needed for local development. it allows for hot-reloading of the server
# omit this in production
root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/storeman"
cmd = "CGO_ENABLED=1 go build -o ./tmp/storeman ./cmd/app"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "data", "node_modules"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
